/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salesmanager;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author j9neave
 */
public class SalesManager extends javax.swing.JFrame {

	private List<Map<String, String>> parsedList = new ArrayList();
	
	/**
	 * Creates new form MainWindow
	 */
	public SalesManager() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Manager");
        setName("Sales Manager"); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("CSV not found");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jButton1, gridBagConstraints);

        jTextField1.setForeground(new java.awt.Color(109, 109, 109));
        jTextField1.setText("Search...");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jTextField1, gridBagConstraints);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Item Name", "Sales Rep", "Sale ID", "Sale Price", "Unit Cost", "Sales Area", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
		JFileChooser chooser = new JFileChooser();
		chooser.setFileFilter(new FileNameExtensionFilter("Comma Separated Values (.csv) Files", "csv"));
		int return_value = chooser.showOpenDialog(this);
		if (return_value == JFileChooser.APPROVE_OPTION) {
			if (chooser.getSelectedFile().exists()) {
				if (chooser.getSelectedFile().getName().endsWith(".csv")) {
					this.setTitle("Sales Manager - " + chooser.getSelectedFile().getAbsolutePath());
					jButton1.setForeground(new java.awt.Color(0, 153, 0));
					jButton1.setText("CSV Found");
					try {
						parseCSV(chooser.getSelectedFile());
					} catch (FileNotFoundException ex) {
						Logger.getLogger(SalesManager.class.getName()).log(Level.SEVERE, null, ex);
					}
				} else {
					jButton1.setText("CSV not found");
					jButton1.setForeground(new java.awt.Color(204, 0, 0));
					this.setTitle("Sales Manager");
				}
			} else {
				jButton1.setText("CSV not found");
				jButton1.setForeground(new java.awt.Color(204, 0, 0));
				this.setTitle("Sales Manager");
			}
		} else {
			jButton1.setText("CSV not found");
			jButton1.setForeground(new java.awt.Color(204, 0, 0));
			this.setTitle("Sales Manager");
		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
		if (jTextField1.getText().equals("Search...")) {
			jTextField1.setForeground(new java.awt.Color(0, 0, 0));
			jTextField1.setText("");
		}
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
		if (jTextField1.getText().equals("")) {
			jTextField1.setForeground(new java.awt.Color(109, 109, 109));
			jTextField1.setText("Search...");
		}

    }//GEN-LAST:event_jTextField1FocusLost

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SalesManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SalesManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SalesManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SalesManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SalesManager().setVisible(true);
			}
		});
	}
	
	private void parseCSV(File csv_file) throws FileNotFoundException {
		try (Scanner csv_scan = new Scanner(csv_file);){
			csv_scan.nextLine();
			while (csv_scan.hasNext()) {
				Map<String, String> parsedLine = new HashMap();
				String line = csv_scan.nextLine();
				String[] separated_line = line.split(",(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)", -1);

				parsedLine.put("ID", separated_line[0]);
				parsedLine.put("Item Name", separated_line[1]);
				parsedLine.put("Sales Rep", separated_line[2]);
				parsedLine.put("Sale ID", separated_line[3]);
				parsedLine.put("Sale Price", separated_line[4]);
				parsedLine.put("Unit Cost", separated_line[5]);
				parsedLine.put("Sales Area", separated_line[6]);
				parsedLine.put("Department", separated_line[7]);
				
				parsedList.add(parsedLine);
				
			}
			
			updateTable();
			
		}
	}
	
	private void updateTable() {
		DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
		for (Map<String, String> line : parsedList) {
			Object[] row = {
				line.get("ID"),
				line.get("Item Name"),
				line.get("Sales Rep"), 
				line.get("Sale ID"),
				line.get("Sale Price"), 
				line.get("Unit Cost"), 
				line.get("Sales Area"),
				line.get("Department")
			};
			model.addRow(row);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
